# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low
{{{ ansible_instantiate_variables("var_logrotate_rotate_count") }}}

- name: Configure daily log rotation in /etc/logrotate.conf
  lineinfile:
    create: yes
    dest: "/etc/logrotate.conf"
    regexp: "^daily$"
    line: "daily"

- name: Make sure daily log rotation setting is not overriden in /etc/logrotate.conf
  lineinfile:
    create: no
    dest: "/etc/logrotate.conf"
    regexp: '^[\s]*(weekly|monthly|yearly)$'
    state: absent

- name: Set rotate count for log rotation schedule
  lineinfile:
    create: yes
    dest: "/etc/logrotate.conf"
    regex: "^rotate.*$"
    line: "rotate {{ var_logrotate_rotate_count }}"

- name: Configure cron.daily if not already
  block:
    - name: Add shebang
      lineinfile:
        path: "/etc/cron.daily/logrotate"
        line: "#!/bin/sh"
        insertbefore: BOF
        create: yes
    - name: Add logrotate call
      lineinfile:
        path: "/etc/cron.daily/logrotate"
        line: '/usr/sbin/logrotate /etc/logrotate.conf'
        regexp: '^[\s]*/usr/sbin/logrotate[\s\S]*/etc/logrotate.conf$'
