# platform = multi_platform_sle,multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_instantiate_variables("var_password_hashing_algorithm") }}}

- name: Add password hashing argument to pam_unix module
  pamd:
    name: common-password
    type: password
{{% if product in ["ubuntu1804", "ubuntu2004"] %}}
    control: '[success=1 default=ignore]'
{{% else %}}
    control: required
{{% endif %}}
    module_path: pam_unix.so
    module_arguments: "{{ var_password_hashing_algorithm | lower }}"
    state: args_present
