# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv,multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_sshd_set(parameter="Protocol", value="2") }}}
