# platform = multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_instantiate_variables("var_password_pam_remember") }}}

{{{ ansible_lineinfile(
  msg="Make changes to /etc/pam.d/common-password",
  path="/etc/pam.d/common-password",
  regex="^\s*password\s+(required|requisite|sufficient|optional)\s+pam_pwhistory.so\s*",
  insert_before="^\s*password.*pam_unix.so",
  new_line="password    requisite     pam_pwhistory.so remember={{ var_password_pam_remember }} retry=2"
) }}}
